package com.dwy.curriculum.model.mapper;

import com.dwy.curriculum.model.domain.Assessment;
import com.dwy.curriculum.model.domain.AssessmentExample;
import com.dwy.curriculum.model.domain.AssessmentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AssessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @SelectProvider(type=AssessmentSqlProvider.class, method="countByExample")
    long countByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @DeleteProvider(type=AssessmentSqlProvider.class, method="deleteByExample")
    int deleteByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @Insert({
        "insert into assessment (id, good, ",
        "star, term_related, ",
        "time, userid, assessment_content)",
        "values (#{id,jdbcType=VARCHAR}, #{good,jdbcType=INTEGER}, ",
        "#{star,jdbcType=DOUBLE}, #{termRelated,jdbcType=INTEGER}, ",
        "#{time,jdbcType=DATE}, #{userid,jdbcType=VARCHAR}, #{assessmentContent,jdbcType=LONGVARCHAR})"
    })
    int insert(AssessmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @InsertProvider(type=AssessmentSqlProvider.class, method="insertSelective")
    int insertSelective(AssessmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @SelectProvider(type=AssessmentSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="good", property="good", jdbcType=JdbcType.INTEGER),
        @Result(column="star", property="star", jdbcType=JdbcType.DOUBLE),
        @Result(column="term_related", property="termRelated", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.DATE),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="assessment_content", property="assessmentContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<AssessmentWithBLOBs> selectByExampleWithBLOBs(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @SelectProvider(type=AssessmentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="good", property="good", jdbcType=JdbcType.INTEGER),
        @Result(column="star", property="star", jdbcType=JdbcType.DOUBLE),
        @Result(column="term_related", property="termRelated", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.DATE),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR)
    })
    List<Assessment> selectByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=AssessmentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AssessmentWithBLOBs record, @Param("example") AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=AssessmentSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") AssessmentWithBLOBs record, @Param("example") AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=AssessmentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Assessment record, @Param("example") AssessmentExample example);
}