package com.dwy.curriculum.model.mapper;

import com.dwy.curriculum.model.domain.AssessmentExample.Criteria;
import com.dwy.curriculum.model.domain.AssessmentExample.Criterion;
import com.dwy.curriculum.model.domain.AssessmentExample;
import com.dwy.curriculum.model.domain.AssessmentWithBLOBs;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class AssessmentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String countByExample(AssessmentExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("assessment");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String deleteByExample(AssessmentExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("assessment");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String insertSelective(AssessmentWithBLOBs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("assessment");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getGood() != null) {
            sql.VALUES("good", "#{good,jdbcType=INTEGER}");
        }
        
        if (record.getStar() != null) {
            sql.VALUES("star", "#{star,jdbcType=DOUBLE}");
        }
        
        if (record.getTermRelated() != null) {
            sql.VALUES("term_related", "#{termRelated,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=DATE}");
        }
        
        if (record.getUserid() != null) {
            sql.VALUES("userid", "#{userid,jdbcType=VARCHAR}");
        }
        
        if (record.getAssessmentContent() != null) {
            sql.VALUES("assessment_content", "#{assessmentContent,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String selectByExampleWithBLOBs(AssessmentExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("good");
        sql.SELECT("star");
        sql.SELECT("term_related");
        sql.SELECT("time");
        sql.SELECT("userid");
        sql.SELECT("assessment_content");
        sql.FROM("assessment");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String selectByExample(AssessmentExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("good");
        sql.SELECT("star");
        sql.SELECT("term_related");
        sql.SELECT("time");
        sql.SELECT("userid");
        sql.FROM("assessment");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AssessmentWithBLOBs record = (AssessmentWithBLOBs) parameter.get("record");
        AssessmentExample example = (AssessmentExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("assessment");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getGood() != null) {
            sql.SET("good = #{record.good,jdbcType=INTEGER}");
        }
        
        if (record.getStar() != null) {
            sql.SET("star = #{record.star,jdbcType=DOUBLE}");
        }
        
        if (record.getTermRelated() != null) {
            sql.SET("term_related = #{record.termRelated,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.SET("time = #{record.time,jdbcType=DATE}");
        }
        
        if (record.getUserid() != null) {
            sql.SET("userid = #{record.userid,jdbcType=VARCHAR}");
        }
        
        if (record.getAssessmentContent() != null) {
            sql.SET("assessment_content = #{record.assessmentContent,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("assessment");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("good = #{record.good,jdbcType=INTEGER}");
        sql.SET("star = #{record.star,jdbcType=DOUBLE}");
        sql.SET("term_related = #{record.termRelated,jdbcType=INTEGER}");
        sql.SET("time = #{record.time,jdbcType=DATE}");
        sql.SET("userid = #{record.userid,jdbcType=VARCHAR}");
        sql.SET("assessment_content = #{record.assessmentContent,jdbcType=LONGVARCHAR}");
        
        AssessmentExample example = (AssessmentExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("assessment");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("good = #{record.good,jdbcType=INTEGER}");
        sql.SET("star = #{record.star,jdbcType=DOUBLE}");
        sql.SET("term_related = #{record.termRelated,jdbcType=INTEGER}");
        sql.SET("time = #{record.time,jdbcType=DATE}");
        sql.SET("userid = #{record.userid,jdbcType=VARCHAR}");
        
        AssessmentExample example = (AssessmentExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    protected void applyWhere(SQL sql, AssessmentExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}