package com.dwy.curriculum.model.mapper;

import com.dwy.curriculum.model.domain.Term;
import com.dwy.curriculum.model.domain.TermExample;
import com.dwy.curriculum.model.domain.TermKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @SelectProvider(type=TermSqlProvider.class, method="countByExample")
    long countByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @DeleteProvider(type=TermSqlProvider.class, method="deleteByExample")
    int deleteByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @Delete({
        "delete from term",
        "where term_id = #{termId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TermKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @Insert({
        "insert into term (term_id, id, ",
        "term_class, term_start, ",
        "term_end, term_serial, ",
        "term_student)",
        "values (#{termId,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, ",
        "#{termClass,jdbcType=VARCHAR}, #{termStart,jdbcType=DATE}, ",
        "#{termEnd,jdbcType=DATE}, #{termSerial,jdbcType=INTEGER}, ",
        "#{termStudent,jdbcType=INTEGER})"
    })
    int insert(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @InsertProvider(type=TermSqlProvider.class, method="insertSelective")
    int insertSelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @SelectProvider(type=TermSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="term_id", property="termId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="term_class", property="termClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="term_start", property="termStart", jdbcType=JdbcType.DATE),
        @Result(column="term_end", property="termEnd", jdbcType=JdbcType.DATE),
        @Result(column="term_serial", property="termSerial", jdbcType=JdbcType.INTEGER),
        @Result(column="term_student", property="termStudent", jdbcType=JdbcType.INTEGER)
    })
    List<Term> selectByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @Select({
        "select",
        "term_id, id, term_class, term_start, term_end, term_serial, term_student",
        "from term",
        "where term_id = #{termId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="term_id", property="termId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="term_class", property="termClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="term_start", property="termStart", jdbcType=JdbcType.DATE),
        @Result(column="term_end", property="termEnd", jdbcType=JdbcType.DATE),
        @Result(column="term_serial", property="termSerial", jdbcType=JdbcType.INTEGER),
        @Result(column="term_student", property="termStudent", jdbcType=JdbcType.INTEGER)
    })
    Term selectByPrimaryKey(TermKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=TermSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=TermSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @UpdateProvider(type=TermSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    @Update({
        "update term",
        "set id = #{id,jdbcType=VARCHAR},",
          "term_class = #{termClass,jdbcType=VARCHAR},",
          "term_start = #{termStart,jdbcType=DATE},",
          "term_end = #{termEnd,jdbcType=DATE},",
          "term_serial = #{termSerial,jdbcType=INTEGER},",
          "term_student = #{termStudent,jdbcType=INTEGER}",
        "where term_id = #{termId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Term record);
}