package com.dwy.curriculum.model.mapper;

import com.dwy.curriculum.model.domain.Term;
import com.dwy.curriculum.model.domain.TermExample.Criteria;
import com.dwy.curriculum.model.domain.TermExample.Criterion;
import com.dwy.curriculum.model.domain.TermExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TermSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String countByExample(TermExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("term");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String deleteByExample(TermExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("term");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String insertSelective(Term record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("term");
        
        if (record.getTermId() != null) {
            sql.VALUES("term_id", "#{termId,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getTermClass() != null) {
            sql.VALUES("term_class", "#{termClass,jdbcType=VARCHAR}");
        }
        
        if (record.getTermStart() != null) {
            sql.VALUES("term_start", "#{termStart,jdbcType=DATE}");
        }
        
        if (record.getTermEnd() != null) {
            sql.VALUES("term_end", "#{termEnd,jdbcType=DATE}");
        }
        
        if (record.getTermSerial() != null) {
            sql.VALUES("term_serial", "#{termSerial,jdbcType=INTEGER}");
        }
        
        if (record.getTermStudent() != null) {
            sql.VALUES("term_student", "#{termStudent,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String selectByExample(TermExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("term_id");
        } else {
            sql.SELECT("term_id");
        }
        sql.SELECT("id");
        sql.SELECT("term_class");
        sql.SELECT("term_start");
        sql.SELECT("term_end");
        sql.SELECT("term_serial");
        sql.SELECT("term_student");
        sql.FROM("term");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Term record = (Term) parameter.get("record");
        TermExample example = (TermExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("term");
        
        if (record.getTermId() != null) {
            sql.SET("term_id = #{record.termId,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getTermClass() != null) {
            sql.SET("term_class = #{record.termClass,jdbcType=VARCHAR}");
        }
        
        if (record.getTermStart() != null) {
            sql.SET("term_start = #{record.termStart,jdbcType=DATE}");
        }
        
        if (record.getTermEnd() != null) {
            sql.SET("term_end = #{record.termEnd,jdbcType=DATE}");
        }
        
        if (record.getTermSerial() != null) {
            sql.SET("term_serial = #{record.termSerial,jdbcType=INTEGER}");
        }
        
        if (record.getTermStudent() != null) {
            sql.SET("term_student = #{record.termStudent,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("term");
        
        sql.SET("term_id = #{record.termId,jdbcType=VARCHAR}");
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("term_class = #{record.termClass,jdbcType=VARCHAR}");
        sql.SET("term_start = #{record.termStart,jdbcType=DATE}");
        sql.SET("term_end = #{record.termEnd,jdbcType=DATE}");
        sql.SET("term_serial = #{record.termSerial,jdbcType=INTEGER}");
        sql.SET("term_student = #{record.termStudent,jdbcType=INTEGER}");
        
        TermExample example = (TermExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String updateByPrimaryKeySelective(Term record) {
        SQL sql = new SQL();
        sql.UPDATE("term");
        
        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=VARCHAR}");
        }
        
        if (record.getTermClass() != null) {
            sql.SET("term_class = #{termClass,jdbcType=VARCHAR}");
        }
        
        if (record.getTermStart() != null) {
            sql.SET("term_start = #{termStart,jdbcType=DATE}");
        }
        
        if (record.getTermEnd() != null) {
            sql.SET("term_end = #{termEnd,jdbcType=DATE}");
        }
        
        if (record.getTermSerial() != null) {
            sql.SET("term_serial = #{termSerial,jdbcType=INTEGER}");
        }
        
        if (record.getTermStudent() != null) {
            sql.SET("term_student = #{termStudent,jdbcType=INTEGER}");
        }
        
        sql.WHERE("term_id = #{termId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    protected void applyWhere(SQL sql, TermExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}