package com.dwy.curriculum.model.domain;

public class AssessmentWithBLOBs extends Assessment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessment.assessment_content
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String assessmentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessment.assessment_content
     *
     * @return the value of assessment.assessment_content
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getAssessmentContent() {
        return assessmentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessment.assessment_content
     *
     * @param assessmentContent the value for assessment.assessment_content
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setAssessmentContent(String assessmentContent) {
        this.assessmentContent = assessmentContent == null ? null : assessmentContent.trim();
    }
}