package com.dwy.curriculum.model.domain;

public class Curriculum extends CurriculumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.name
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.category
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.assessment_number
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Integer assessmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.assessment_score
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Double assessmentScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.university
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String university;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.universityId
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Integer universityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.name
     *
     * @return the value of curriculum.name
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.name
     *
     * @param name the value for curriculum.name
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.category
     *
     * @return the value of curriculum.category
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.category
     *
     * @param category the value for curriculum.category
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.assessment_number
     *
     * @return the value of curriculum.assessment_number
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Integer getAssessmentNumber() {
        return assessmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.assessment_number
     *
     * @param assessmentNumber the value for curriculum.assessment_number
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setAssessmentNumber(Integer assessmentNumber) {
        this.assessmentNumber = assessmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.assessment_score
     *
     * @return the value of curriculum.assessment_score
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Double getAssessmentScore() {
        return assessmentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.assessment_score
     *
     * @param assessmentScore the value for curriculum.assessment_score
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setAssessmentScore(Double assessmentScore) {
        this.assessmentScore = assessmentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.university
     *
     * @return the value of curriculum.university
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.university
     *
     * @param university the value for curriculum.university
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setUniversity(String university) {
        this.university = university == null ? null : university.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.universityId
     *
     * @return the value of curriculum.universityId
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Integer getUniversityid() {
        return universityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.universityId
     *
     * @param universityid the value for curriculum.universityId
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setUniversityid(Integer universityid) {
        this.universityid = universityid;
    }
}