package com.dwy.curriculum.model.domain;

public class CurriculumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum.id
     *
     * @return the value of curriculum.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum.id
     *
     * @param id the value for curriculum.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}