package com.dwy.curriculum.model.domain;

import java.util.Date;

public class Term extends TermKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_class
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String termClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_start
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Date termStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_end
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Date termEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_serial
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Integer termSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_student
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private Integer termStudent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.id
     *
     * @return the value of term.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.id
     *
     * @param id the value for term.id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_class
     *
     * @return the value of term.term_class
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getTermClass() {
        return termClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_class
     *
     * @param termClass the value for term.term_class
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermClass(String termClass) {
        this.termClass = termClass == null ? null : termClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_start
     *
     * @return the value of term.term_start
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Date getTermStart() {
        return termStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_start
     *
     * @param termStart the value for term.term_start
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermStart(Date termStart) {
        this.termStart = termStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_end
     *
     * @return the value of term.term_end
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Date getTermEnd() {
        return termEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_end
     *
     * @param termEnd the value for term.term_end
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermEnd(Date termEnd) {
        this.termEnd = termEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_serial
     *
     * @return the value of term.term_serial
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Integer getTermSerial() {
        return termSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_serial
     *
     * @param termSerial the value for term.term_serial
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermSerial(Integer termSerial) {
        this.termSerial = termSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_student
     *
     * @return the value of term.term_student
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public Integer getTermStudent() {
        return termStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_student
     *
     * @param termStudent the value for term.term_student
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermStudent(Integer termStudent) {
        this.termStudent = termStudent;
    }
}