package com.dwy.curriculum.model.domain;

public class TermKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    private String termId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_id
     *
     * @return the value of term.term_id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public String getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_id
     *
     * @param termId the value for term.term_id
     *
     * @mbg.generated Wed Jan 20 14:25:41 CST 2021
     */
    public void setTermId(String termId) {
        this.termId = termId == null ? null : termId.trim();
    }
}